# what it is
Traffic generator is a simple bash script that records the network
traffic generated by andriod apps. 

# dependencies
Make sure that the folder "platform-tools" and "tools" of the andriod SDK are
within you local lookup path. Furthermore yoo have to create a virtual device profile for andriod 1.5 or higher. The command below creates a new virtual profile.
    android create avd -n td -t 1
You have to make sure that you have installed at least andriod 1.5 SDK within
the andriod SDK and AVD manager.

Attention: Currently the script assumes that the profiles name is "td"

# how to run

    ./tragen.sh <dir>
    <dir> path to directory containing at least one andriod app

# remark
The file _AXMLPrinter2.jar_ is not my intellectual property.
The project homepage can be found at http://code.google.com/p/android4me/
